variables:
  SECURE_LOG_LEVEL: Debug
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - module-pipelines
  - deploy

frontend:
  stage: module-pipelines
  trigger:
    include:
    - "/frontend/.gitlab-ci.yml"
    strategy: depend

backend:
  stage: module-pipelines
  trigger:
    include:
    - "/backend/.gitlab-ci.yml"
    strategy: depend

deploy:
  stage: deploy
  image: argoproj/argocd:v2.3.3
  script:
    - echo "deploy to k8s - argocd"
    - argocd login argo.momo-store.ml --username admin --password ${ARGO_PAS} --insecure
    - argocd --grpc-web --server argo.momo-store.ml app sync app
